name: NPM Publish

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "12.x"
          cache: "npm"

      - name: Install Dependences
        run: npm install

      - name: Build Javascript
        run: npm run build
