name: Typescript Build

on:
  push:
    branch: [ master ]
  pull_request:
    branch: [ master ]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "12.x"
          cache: "npm"
          registry-url: https://registry.npmjs.org/

      - name: Install Dependences
        run: npm install

      - name: Build Javascript
        run: npm run build
